import { type Module, inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import { MachineGeneratedModule, MachineGeneratedSharedModule } from './generated/module.js';
import { MachineValidator, MachineValidationRegistry } from './machine-validator.js';
import { MachineScopeProvider } from './machine-scope.js';
import { MachineSemanticTokenProvider } from './machine-semantic-token-provider.js';
import { Node } from './generated/ast.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type MachineAddedServices = {
    validation: {
        MachineValidator: MachineValidator
    }
}

export interface Edge {
    source: string;
    value: Record<string, any>;
    target: string;
    arrowType?: string;  // Arrow type for relationship mapping
    sourceMultiplicity?: string;  // Source multiplicity (e.g., "1", "*", "0..1")
    targetMultiplicity?: string;  // Target multiplicity (e.g., "1", "*", "1..*")
    style?: EdgeStyle;  // Custom styling for the edge
    roleName?: string;  // Role name for bidirectional relationships
}

export interface EdgeStyle {
    stroke?: string;  // Stroke color
    strokeWidth?: string;  // Stroke width
    strokeDasharray?: string;  // Dash pattern
}

export interface NoteInfo {
    target: string;  // Node name
    content: string;  // Note content
}

export interface InferredDependency {
    source: string;
    target: string;
    reason: string;
    path: string;
}

export interface MachineJSON {
    title: string;
    nodes: Node[];
    edges: Edge[];
    notes?: NoteInfo[];
    inferredDependencies?: InferredDependency[];
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type MachineServices = LangiumServices & MachineAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const MachineModule: Module<MachineServices, PartialLangiumServices & MachineAddedServices> = {
    validation: {
        ValidationRegistry: (services) => new MachineValidationRegistry(services),
        MachineValidator: () => new MachineValidator()
    },
    lsp: {
        SemanticTokenProvider: (services) => new MachineSemanticTokenProvider(services)
    },
    references: {
        ScopeProvider: (services) => new MachineScopeProvider(services)
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createMachineServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    Machine: MachineServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        MachineGeneratedSharedModule
    );
    const Machine = inject(
        createDefaultModule({ shared }),
        MachineGeneratedModule,
        MachineModule
    );
    shared.ServiceRegistry.register(Machine);

    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, Machine };
}
